# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# dongle
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

# how many peripherals can the central role connect to
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
